# Exploratory Data Analysis

Exploratory Data Analysis (EDA) is used by data analysts, and data scientists to analyse and examine data sets and summarise their key features. This is often done by employing data visualisation techniques. EDA helps to determine how data sources can be manipulated to provide the answers required, making it easier for data scientists to spot patterns, uncover anomalies, test hypotheses and confirm assumptions. The main purpose of EDA is to check the data before making hypotheses. EDA not only identifies obvious errors, but also allows us to better understand patterns in the data, detect outliers and unusual events, and find interesting relationships between variables.
In this tutorial, we use Python for EDA to identify missing values in a dataset, which is important to help us decide how to handle missing values for solving machine learning tasks. 

We can use EDA these to find shape of datasets, descriptive statistics of the dataset, correlation between the features in a dataset, acquiring more information about the data from each data frame, checking out the missing values in the data, encoding categorical features etc.

Here, we will solve three examples and look into the details of how EDA works to analyze the raw data.
The link to the datasets is given in below links. You can download from there and use it while you implement this source code.

Example 01: Wine dataset. This can be downloaded directly on the fly.

Example 02: housing.csv https://drive.google.com/file/d/1vIbj_Ek6kGEGcmmw5MxgF4IoyIg3W0T9/view?usp=sharing

# Example 01

In [1]:
#First we import the preliminaries.
import pandas as pd
import numpy as np
#the wine dataset can be downloaded directly using the following link.
#This dataset has 14 features 
df_wine = pd.read_csv('http://archive.ics.uci.edu/'
                      'ml/machine-learning-databases/wine/wine.data',
                      header=None)

In [2]:
df_wine

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

The features are in numerical format, so we can define those features by assigning them name.

In [3]:
df_wine.columns = ['Class label', 'Alcohol', 'Malic acid', 'Ash',
                   'Alcalinity of ash', 'Magnesium', 'Total phenols',
                   'Flavanoids', 'Nonflavanoid phenols', 'Proanthocyanins',
                   'Color intensity', 'Hue', 'OD280/OD315 of diluted wines',
                   'Proline']
df_wine

,Class label,Alcohol,Malic acid,Ash,Alcalinity of ash,Magnesium,Total phenols,Flavanoids,Nonflavanoid phenols,Proanthocyanins,Color intensity,Hue,OD280/OD315 of diluted wines,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,3,13.71,5.65,2.45,20.5,95,1.68,0.61,0.52,1.06,7.70,0.64,1.74,740
174,3,13.40,3.91,2.48,23.0,102,1.80,0.75,0.43,1.41,7.30,0.70,1.56,750
175,3,13.27,4.28,2.26,20.0,120,1.59,0.69,0.43,1.35,10.20,0.59,1.56,835
176,3,13.17,2.59,2.37,20.0,120,1.65,0.68,0.53,1.46,9.30,0.60,1.62,840
177,3,14.13,4.10,2.74,24.5,96,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560

In [4]:
#class_label is the first coloumn of the dataframe. so now lets check how many labels are in this dataset.
df_wine['Class label']
print('Class labels', np.unique(df_wine['Class label']))

Class labels [1 2 3]

In [5]:
#lets ccheck the information about the dataframe. Here we can check the data types and null count
df_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Class label                   178 non-null    int64
 1   Alcohol                       178 non-null    float64
 2   Malic acid                    178 non-null    float64
 3   Ash                           178 non-null    float64
 4   Alcalinity of ash             178 non-null    float64
 5   Magnesium                     178 non-null    int64
 6   Total phenols                 178 non-null    float64
 7   Flavanoids                    178 non-null    float64
 8   Nonflavanoid phenols          178 non-null    float64
 9   Proanthocyanins               178 non-null    float64
 10  Color intensity               178 non-null    float64
 11  Hue                           178 non-null    float64
 12  OD280/OD315 of diluted wines  178 non-null    float64
 13  Proline                       178 non-null    int64
dtypes: float64(11), int64(3)
memory usage: 19.6 KB

In [6]:
#Now that we have our features and labels, we can separate it into training and testing purpose.
#We donot employ a machine learning model in this algorithm, instead we just see how the dataset can
#be prepared for a machine learning model. However, you can use any ML models after here on.
from sklearn.model_selection import train_test_split

X, y = df_wine.iloc[:, 1:].values, df_wine.iloc[:, 0].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0, stratify=y)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(124, 13)
(54, 13)
(124,)
(54,)

# Exampe 02: Now lets dive more into the EDA.

In [7]:
import numpy as np
import os #Execute the functions provided by the operating system
import matplotlib
import matplotlib.pyplot as plt
import pandas as pd

path = os.path.join("housing.csv") #can be downloaded from the link provided above.
housing = pd.read_csv(path)
housing.head()

FileNotFoundError: [Errno 2] No such file or directory: 'housing.csv'

In [ ]:
housing.info()

In [ ]:
housing.describe()

In [ ]:
#Now lets plot the data distribution of each features.
#For this we Create a histogram with 50 bars
#Histogram plot allows to discover and show the underlying frequency distribution of the data.
#This can be done to inspect the data to check its distribution, and finding the outliers.
housing.hist(bins=50, figsize=(20,15))
plt.show()

In the next step we use scatter plotting to visualize the feature of the dataset. A scatter plot uses dots to represent values for two different numeric variables. The position of each dot on the horizontal and vertical axis indicates values for an individual data point. Scatter plots are used to observe relationships between variables.

In [ ]:
housing.plot(kind="scatter", x="longitude", y="latitude", alpha=0.1) # alpha : density measure
plt.show()

Scatter plotting can be done by color mapping the specific feature. For example, below we color map the population variable and show which location (latitude/longitude) consists of dense population.

In [ ]:
housing.plot(kind="scatter", x="longitude", y="latitude", alpha=0.3,
    s=housing["population"]/100, label="population", figsize=(10,7),
    c="median_house_value", cmap=plt.get_cmap("jet"), colorbar=True,
    sharex=False) # s: size, c: color reference, cmap: mapping option
plt.legend()
plt.show()

Correlation: They can be used to investigate the dependence between multiple variables at the same time and to highlight the most correlated variables in a data table. In this visual, correlation coefficients are colored according to the value.
A correlation coefficient of 1 means that for every positive increase in one variable, there is a positive increase of a fixed proportion in the other. For example, shoe sizes go up in (almost) perfect correlation with foot length.

A correlation coefficient of -1 means that for every positive increase in one variable, there is a negative decrease of a fixed proportion in the other. For example, the amount of gas in a tank decreases in (almost) perfect correlation with speed.

Zero means that for every increase, there isnâ€™t a positive or negative increase. The two just arenâ€™t related.

#Pearson's correlation coefficient, 1: positive slope, -1: negative slope, 0: means that there is no data relationship, but that it is difficult to express linearly.

In [ ]:
corr_matrix = housing.corr()
print(corr_matrix["median_house_value"].sort_values(ascending=False)) # Sort in order of correlation coefficient

In [ ]:
print(corr_matrix["median_income"].sort_values(ascending=False))

Now lets create scatter matrix of all featurs of the data and see the realtionship between the variables. As we go from left to right in the scatter plot, the uphill pattern shows there is positive relation between two variables, and if opposite then there is negative relationship.

In [ ]:
#importing scatter_matric from pandas plotting library
from pandas.plotting import scatter_matrix
scatter_matrix(housing, figsize=(12, 8))
plt.show()

To plot the correlation map, we can use seaborn library from python. To install go to this link :https://seaborn.pydata.org/installing.html
Seaborn is a Python data visualization library based on matplotlib. It provides a high-level interface for drawing attractive and informative statistical graphics.

In [ ]:
import seaborn as sns
plt.figure(figsize=(15,15))
sns.heatmap(corr_matrix, annot=True, fmt = '.2f', linewidths=.5, cmap='Blues')# annot: cell value display, fmt: number display format

The standard correlation with median_house_value was quite low, so it was not very helpful to view it as an independent variable.
However, from the above correlation plot we can see that there is a high correlation between these variables (total rooms, total bedrooms, population, and households), so now lets create more meaningful representations by using those variables.

In [ ]:
attributes = ["total_rooms", "households", "total_bedrooms", "population"] 
scatter_matrix(housing[attributes], figsize=(12, 8))
plt.show()
print(housing[attributes].corr())

Now lets create three new variables in our data and check their correlation.

In [ ]:
# Create three new variables
housing["rooms_per_household"] = housing["total_rooms"]/housing["households"] #new variable 1
housing["bedrooms_per_room"] = housing["total_bedrooms"]/housing["total_rooms"] #new vairable 2
housing["population_per_household"]=housing["population"]/housing["households"] #new variable 3
corr_matrix = housing.corr()
print(corr_matrix["median_house_value"].sort_values(ascending=False)) #rooms_per_household , bedrooms_per_room has a greater correlation than the existing variable